-- HR.공연 definition
CREATE TABLE "HR"."공연"
(	"공연ID" VARCHAR2(100) NOT NULL ENABLE,
"제목" VARCHAR2(100) NOT NULL ENABLE,
"위치" VARCHAR2(100) NOT NULL ENABLE,
"공연시작일" DATE NOT NULL ENABLE,
"공연종료일" DATE NOT NULL ENABLE,
"가격" NUMBER(38,0) NOT NULL ENABLE,
CONSTRAINT "공연_PK" PRIMARY KEY ("공연ID")
);
CREATE UNIQUE INDEX "HR"."공연_PK" ON "HR"."공연" ("공연ID") ;
 
-- HR.예매자 definition
CREATE TABLE "HR"."예매자"
(	"전화번호" VARCHAR2(100),
"이메일" VARCHAR2(100),
"이름" VARCHAR2(100) NOT NULL ENABLE,
CONSTRAINT "예매자_PK" PRIMARY KEY ("전화번호")
) ;
CREATE UNIQUE INDEX "HR"."예매자_PK" ON "HR"."예매자" ("전화번호") ;

-- HR.예매정보 definition
CREATE TABLE "HR"."예매정보" 
   (	"예매번호" NUMBER(38,0) NOT NULL ENABLE, 
	"공연ID" VARCHAR2(100) NOT NULL ENABLE, 
	"예매전화번호" VARCHAR2(100) NOT NULL ENABLE, 
	"예매일자" DATE NOT NULL ENABLE, 
	 CONSTRAINT "예매정보_PK" PRIMARY KEY ("예매번호")
   ) ;
  
-- HR.예매정보 foreign keys
ALTER TABLE "HR"."예매정보" ADD CONSTRAINT "FK_공연" FOREIGN KEY ("공연ID")
	  REFERENCES "HR"."공연" ("공연ID") ENABLE;
ALTER TABLE "HR"."예매정보" ADD CONSTRAINT "FK_예매자" FOREIGN KEY ("예매전화번호")
	  REFERENCES "HR"."예매자" ("전화번호") ENABLE;

-- HR.관리자 definition
CREATE TABLE "HR"."관리자"
(	"ID" VARCHAR2(100),
"PW" VARCHAR2(100)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;